### PR TITLE
Clean and better hook for Sage

### PR DESCRIPTION
**Pull request by tscrim**
I've tried to go through and clean the code a bit (not completely, but it is more readable IMO). I also added a function so that we can get the output as a polynomial. We might also want to have a similar function which takes the string as input and gives a polynomial back.

### CODE REVIEW

**Comment by tscrim** [comment]
I should state that I have _not_ tested this yet

**Comment by tscrim** [comment]
Still a few things to work out currently...

**Comment by miguelmarco** [comment]
I see that what you did is mostly style changes, rename certain variables and types,  and eliminate some checks for directives. But there are some other changes that I am not so sure about (mainly because my C is not as good as i would like).

It seems that you are moving several types from pointers to actual variables. Is it safe to do so?

**Comment by tscrim** [comment]
Some of the things I did were not correct because the pointer itself is changed and needs to be changed further up. I should have fixed these, but I still can't quite build it for testing yet...almost there.

I haven't done proper C coding in quite a long time. I miss pass-by-reference of C++...

**Comment by tscrim** [comment]
Only thing left to do now is to actually get things to link to finally test properly...

**Comment by tscrim** [comment]
Okay, the test program works.

**Comment by tscrim** [comment]
I realized the test program was not actually doing the test properly. I have fixed this in the PR.

**Comment by miguelmarco** [comment]
So if I understood correctly, now the function to be exposed would be homfly_str, that returns a string from a string, right?

**Comment by tscrim** [comment]
What I want to do is expose `homfly` and also implement Cython code for `Poly` and convert that to a Sage polynomial instead of doing string parsing.

However, yes, we can also expose `homfly_str` too if string output is desired.

**Comment by miguelmarco** [comment]
Ok, that sounds optimal. Although That would need also some code from the cython interface part. Do you think it would be worth to also skip the string conversion in the input, and pass an array of `crossing` ?

**Comment by tscrim** [comment]
I had thought about that, but I'm not completely sure I understand the data structure used in homflylib. However, I am in favor of doing that.

**Comment by tscrim** [comment]
However, in the library, there looks like a desire for a link struct, but that is a separate issue (see #2).

**Comment by miguelmarco** [comment]
We have to look at the `k_read` function. If the parsing of the string it does is complicated, I thing it would be better to leave the library handle that. Constructing the string from the Sage side is almost trivial (it is essentially the oriented gauss code). If we need to do a complicated preprocessing befire calling the library, we might be loosing partly the advantage of having a library that does that hard work.

**Comment by tscrim** [comment]
Parsing the string and building the data to feed to construct the homfly polynomial are different problems to me. However, I agree that looking into `k_read` will likely give hints/guidance on how to construct the data. I also agree that we should not re-implement the string processing on our side.

**Comment by tscrim** [comment]
I will take a look at this tonight. (Right now I am going to be working on improving simplicial complexes, homology, and manifolds in Sage.)

**Comment by miguelmarco** [comment]
Ok, I see some with the headers though: if we copy header files like "standard.h", "order.h" or "poly.h"... we will have name conflicts at some point.

**Comment by tscrim** [comment]
IDK how much of an issue that will be. I guess I (we?) will have to experiment.

**Comment by miguelmarco** [comment]
I am trying to work on that, by putting just in one header file ("homfly.h") all the needed type definitions

**Comment by tscrim** [comment]
Great, thanks!

**Pull request merged**
