### PR TITLE
Implementing a Link struct and improving testing

### PR DESCRIPTION
**Pull request by tscrim**
I've done #2 by implementing a `struct Link` in a minimal way, but it does make the function calls cleaner and easier to follow.

I've improved the testing so that it is no longer hard coded but instead takes a (very specifically formatted) data file as input. Since this is just meant to be mostly lightweight testing, I think a cheap implementation is okay. If we wanted something more robust, I could re-implement some things of the testing in C++ or python, but that would likely require a more complicated build system.

With that, I am done editing.

### CODE REVIEW

**Comment by tscrim** [comment]
Okay, I need to implement the additional test data on this side

**Comment by tscrim** [comment]
I had to fight a little bit with the line endings, but I got the test suite working. (For some reason my editor wanted to make everything end like it was in windows.)

Once this PR is done, you can cut a new tarball/release and we can include that into Sage.

**Comment by miguelmarco** [comment]
Right now, `make test` doesn't do anything, does it?

Also, I would like to fix som subtleties about the symbols exposed (the library should expose `homfly_str`, `homfly` and `c_homfly`, right?

**Comment by tscrim** [comment]
`make check` runs the test suite, which in turn runs the `tests/run_tests` script.

Go ahead and fix what you need to.

**Comment by miguelmarco** [comment]
I have pushed a small change in the Makefile.am that makes the compiler expose the three _homfly_ symbols.

**Pull request merged**
